# Generated by Django 5.2.4 on 2025-07-12 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('teste', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_competence', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_domaine', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_poste', models.CharField(max_length=100)),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recrutement.domaine')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_test', models.DateTimeField(auto_now_add=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recrutement.candidat')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recrutement.responsable')),
            ],
        ),
        migrations.CreateModel(
            name='CandidatCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.IntegerField()),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recrutement.candidat')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recrutement.competence')),
            ],
            options={
                'unique_together': {('candidat', 'competence')},
            },
        ),
        migrations.CreateModel(
            name='AppartenanceCompetencePoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.FloatField()),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recrutement.competence')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recrutement.poste')),
            ],
            options={
                'unique_together': {('poste', 'competence')},
            },
        ),
        migrations.CreateModel(
            name='ResultatTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_evalue', models.IntegerField()),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recrutement.competence')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recrutement.test')),
            ],
            options={
                'unique_together': {('test', 'competence')},
            },
        ),
    ]
