# Generated by Django 5.2.4 on 2025-07-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='motdepasse',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsable',
            name='motdepasse',
            field=models.CharField(default='00001111', max_length=128),
            preserve_default=False,
        ),
    ]
