# Generated by Django 5.2.4 on 2025-07-18 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0002_candidat_motdepasse_responsable_motdepasse'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatPoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tester', models.BooleanField(default=False)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recrutement.candidat')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recrutement.poste')),
            ],
            options={
                'verbose_name': 'Association Candidat-Poste',
                'verbose_name_plural': 'Associations Candidat-Poste',
                'unique_together': {('candidat', 'poste')},
            },
        ),
    ]
